### PR TITLE
FizzBuzz- python

### PR DESCRIPTION
**Pull request by sukeshni**

### CODE REVIEW

**Comment by sukeshni** [comment]
@shunjikonishi Please Review

**Comment by shunjikonishi** [comment]
@sukeshni fix me
No test run.

```
$ codecheck
codecheck version 0.4.2

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK
codecheck: Finish with code 0
codecheck: tests  : 0
codecheck: success: 0
codecheck: failure: 0
```

**Comment by sukeshni** [comment]
@shunjikonishi Fixed. Please review.

**Comment by shunjikonishi** [comment]
Current version of codecheck command can not get the number of tests/success/failure.
Because this test has only 1 testcase.

https://github.com/code-check/codecheck/pull/38

LGTM

**Pull request closed without merging**
