### PR TITLE
fizzbuzz for C++

### PR DESCRIPTION
**Pull request by sukeshni**
@shunjikonishi Please review

### CODE REVIEW

**Comment by shunjikonishi** [comment]
### README.md is wrong

I think this challenge should be only simple FizzBuzz problem.
So,
- Q3 is not necessary. Also q3.md file is not necessary.
- Also Q1 and Q2 are redundancy. You can unify them.

### function name

If you name the function `isXXXX`, it is better to return boolean.

In this case, comfortable function name is just `fizzbuzz` and it return string.
And move printf to main.

### struct data is redundancy.

You can use string.

### Test

This test verifies the results of 1 to 100 in 1 test case.
It is better to split them.

I'll show example later.

@sukeshni fix me
FYI @da0shi

**Comment by shunjikonishi** [comment]
Test example.

https://gist.github.com/shunjikonishi/19a8aaed4577389df9e0

**Comment by shunjikonishi** [comment]
@sukeshni 
About README and test. 
It is better to modify for other languages too.

**Comment by sukeshni** [comment]
@shunjikonishi :+1:

**Comment by sukeshni** [comment]
@shunjikonishi Fixed all your points. Please review.

**Comment by shunjikonishi** [comment]
@sukeshni fix me
Segment fault with following commands.

```
$./a.out
$./a.out 1 2
```

**Comment by sukeshni** [comment]
@shunjikonishi Fixed. Please review

**Comment by shunjikonishi** [comment]
LGTM

**Pull request closed without merging**
